import { anthropic, DEFAULT_MODEL } from "@/lib/agents/client";
import { retrieveSources } from "@/lib/agents/researcher";
import {
  storytellerSystemPrompt,
  storytellerUserPrompt,
} from "@/lib/agents/storyteller";
import { getPersona, getWalk } from "@/lib/data";
import { NextRequest } from "next/server";

export const runtime = "nodejs";

export async function POST(req: NextRequest) {
  const { walkId, stopId, personaId } = await req.json();

  const walk = getWalk(walkId);
  const persona = getPersona(personaId);
  const stop = walk?.stops.find((s) => s.id === stopId);

  if (!walk || !persona || !stop) {
    return new Response("not found", { status: 404 });
  }

  const sources = await retrieveSources(stopId, persona.prompting_profile);

  // If corpus is empty (day 1 — normal), stream a placeholder
  // so the UI works end-to-end before day 2 curation.
  if (sources.length === 0) {
    const placeholder = `[Day 1 placeholder] You are standing at ${stop.name}. ${stop.subtitle}. The corpus has not been curated yet — Day 2 will add primary sources, after which this narrative will be generated by the storyteller agent for ${persona.label}.`;
    return new Response(streamText(placeholder), {
      headers: { "Content-Type": "text/plain; charset=utf-8" },
    });
  }

  const stream = await anthropic().messages.stream({
    model: DEFAULT_MODEL,
    max_tokens: 600,
    system: storytellerSystemPrompt(),
    messages: [
      { role: "user", content: storytellerUserPrompt(stop, persona, sources) },
    ],
  });

  const encoder = new TextEncoder();
  const readable = new ReadableStream({
    async start(controller) {
      try {
        for await (const chunk of stream) {
          if (
            chunk.type === "content_block_delta" &&
            chunk.delta.type === "text_delta"
          ) {
            controller.enqueue(encoder.encode(chunk.delta.text));
          }
        }
        controller.close();
      } catch (err) {
        controller.error(err);
      }
    },
  });

  return new Response(readable, {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
}

function streamText(text: string): ReadableStream<Uint8Array> {
  const encoder = new TextEncoder();
  return new ReadableStream({
    async start(controller) {
      const words = text.split(" ");
      for (const w of words) {
        controller.enqueue(encoder.encode(w + " "));
        await new Promise((r) => setTimeout(r, 30));
      }
      controller.close();
    },
  });
}
